import { LeaderboardEntry, PlayerStats, AchievementBadge } from './types';

/**
 * Mock leaderboard data featuring 20 fantasy-themed players.
 * Each player has RPG-style names and realistic stat distributions.
 */
export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    id: '1',
    name: 'Thalindra Goldweaver',
    address: '0xA1b2...C3d4',
    rank: 1,
    xp: 14850,
    questsCompleted: 47,
    level: 32,
    achievements: ['first-quest', 'speed-demon', 'chain-master', 'legendary-scholar'],
    lastActive: new Date(Date.now() - 300000),
    streak: 12,
  },
  {
    id: '2',
    name: 'Korvash the Unyielding',
    address: '0xE5f6...G7h8',
    rank: 2,
    xp: 13200,
    questsCompleted: 42,
    level: 29,
    achievements: ['first-quest', 'chain-master', 'legendary-scholar'],
    lastActive: new Date(Date.now() - 600000),
    streak: 8,
  },
  {
    id: '3',
    name: 'Seraphina Dawnblade',
    address: '0xI9j0...K1l2',
    rank: 3,
    xp: 12750,
    questsCompleted: 40,
    level: 28,
    achievements: ['first-quest', 'speed-demon', 'chain-master'],
    lastActive: new Date(Date.now() - 900000),
    streak: 15,
  },
  {
    id: '4',
    name: 'Draven Ashenmoor',
    address: '0xM3n4...O5p6',
    rank: 4,
    xp: 11500,
    questsCompleted: 38,
    level: 26,
    achievements: ['first-quest', 'chain-master'],
    lastActive: new Date(Date.now() - 1800000),
    streak: 5,
  },
  {
    id: '5',
    name: 'Lyraen Stormcaller',
    address: '0xQ7r8...S9t0',
    rank: 5,
    xp: 10800,
    questsCompleted: 35,
    level: 24,
    achievements: ['first-quest', 'speed-demon'],
    lastActive: new Date(Date.now() - 3600000),
    streak: 3,
  },
  {
    id: '6',
    name: 'Morghain Ironfist',
    address: '0xU1v2...W3x4',
    rank: 6,
    xp: 9950,
    questsCompleted: 33,
    level: 22,
    achievements: ['first-quest', 'chain-master'],
    lastActive: new Date(Date.now() - 7200000),
    streak: 7,
  },
  {
    id: '7',
    name: 'Zephyria Moonveil',
    address: '0xY5z6...A7b8',
    rank: 7,
    xp: 9200,
    questsCompleted: 31,
    level: 21,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 5400000),
    streak: 4,
  },
  {
    id: '8',
    name: 'Valdris the Eternal',
    address: '0xC9d0...E1f2',
    rank: 8,
    xp: 8750,
    questsCompleted: 29,
    level: 20,
    achievements: ['first-quest', 'speed-demon'],
    lastActive: new Date(Date.now() - 14400000),
    streak: 2,
  },
  {
    id: '9',
    name: 'Ignara Flameheart',
    address: '0xG3h4...I5j6',
    rank: 9,
    xp: 8100,
    questsCompleted: 27,
    level: 19,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 10800000),
    streak: 6,
  },
  {
    id: '10',
    name: 'Thornwick Deeproot',
    address: '0xK7l8...M9n0',
    rank: 10,
    xp: 7500,
    questsCompleted: 25,
    level: 18,
    achievements: ['first-quest', 'chain-master'],
    lastActive: new Date(Date.now() - 21600000),
    streak: 1,
  },
  {
    id: '11',
    name: 'Celestine Starfire',
    address: '0xO1p2...Q3r4',
    rank: 11,
    xp: 6900,
    questsCompleted: 23,
    level: 17,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 28800000),
    streak: 9,
  },
  {
    id: '12',
    name: 'Brakthor Stonefang',
    address: '0xS5t6...U7v8',
    rank: 12,
    xp: 6350,
    questsCompleted: 21,
    level: 16,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 43200000),
    streak: 3,
  },
  {
    id: '13',
    name: 'Vaeloria Nightwhisper',
    address: '0xW9x0...Y1z2',
    rank: 13,
    xp: 5800,
    questsCompleted: 19,
    level: 15,
    achievements: ['first-quest', 'speed-demon'],
    lastActive: new Date(Date.now() - 36000000),
    streak: 2,
  },
  {
    id: '14',
    name: 'Grimshaw the Bold',
    address: '0xA3b4...C5d6',
    rank: 14,
    xp: 5200,
    questsCompleted: 17,
    level: 14,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 50400000),
    streak: 4,
  },
  {
    id: '15',
    name: 'Nimara Windwalker',
    address: '0xE7f8...G9h0',
    rank: 15,
    xp: 4700,
    questsCompleted: 15,
    level: 13,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 57600000),
    streak: 1,
  },
  {
    id: '16',
    name: 'Orcrist Doomforge',
    address: '0xI1j2...K3l4',
    rank: 16,
    xp: 4200,
    questsCompleted: 14,
    level: 12,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 72000000),
    streak: 5,
  },
  {
    id: '17',
    name: 'Faelan Embercrest',
    address: '0xM5n6...O7p8',
    rank: 17,
    xp: 3750,
    questsCompleted: 12,
    level: 11,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 86400000),
    streak: 2,
  },
  {
    id: '18',
    name: 'Mirael Frostvein',
    address: '0xQ9r0...S1t2',
    rank: 18,
    xp: 3200,
    questsCompleted: 10,
    level: 10,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 100800000),
    streak: 3,
  },
  {
    id: '19',
    name: 'Ulric Shadowmend',
    address: '0xU3v4...W5x6',
    rank: 19,
    xp: 2800,
    questsCompleted: 9,
    level: 9,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 115200000),
    streak: 1,
  },
  {
    id: '20',
    name: 'Astraea Runebound',
    address: '0xY7z8...A9b0',
    rank: 20,
    xp: 2350,
    questsCompleted: 7,
    level: 8,
    achievements: ['first-quest'],
    lastActive: new Date(Date.now() - 129600000),
    streak: 1,
  },
];

/** Aggregate stats for the leaderboard overview */
export const MOCK_STATS: PlayerStats = {
  totalPlayers: 1247,
  totalQuestsCompleted: 8934,
  totalXpEarned: 156200,
  activePlayers: 342,
};

/** Achievement badge definitions */
export const ACHIEVEMENT_BADGES: AchievementBadge[] = [
  {
    id: 'first-quest',
    name: 'First Steps',
    icon: '🏁',
    description: 'Completed your first quest',
    rarity: 'common',
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    icon: '⚡',
    description: 'Completed a quest in under 2 minutes',
    rarity: 'rare',
  },
  {
    id: 'chain-master',
    name: 'Chain Master',
    icon: '🔗',
    description: 'Completed 10 quests without failing',
    rarity: 'epic',
  },
  {
    id: 'legendary-scholar',
    name: 'Legendary Scholar',
    icon: '📜',
    description: 'Achieved maximum score on 5 quests',
    rarity: 'legendary',
  },
];
